development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: lesa
  password: lesa

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: lesa
  password: lesa